### ISSUE TITLE
Distband Crashes Ardour4 when Plugin Analysis is opened.

### ISSUE THREAD

**Issue by rcspam** [ssj71/rkrlv2#3] opened 2015-08-03 11:17 UTC
Hi,
It doesn't load in carla2
(Ubuntu 14.04 + KxStufio repo)

**Comment by ssj71** [comment] 2015-08-03 16:42
which effect? I've tested it a fair bit with carla2 but perhaps I missed something?

**Comment by rcspam** [comment] 2015-08-03 16:48
It's ok now i have delete all carla conf files and reinstal itl from scratch, issue surely due to too old home config which we hang out versions after versions. Sorry for this issue

**Comment by ssj71** [comment] 2015-08-03 16:51
no problem. Thanks for the report!

**Comment by rcspam** [comment] 2015-08-03 16:55
Bw, if i test rkr from ardour 4 (without jack session) , gui lv2 doen't works as expected...
![image](https://cloud.githubusercontent.com/assets/10021906/9042712/efa96e58-3a10-11e5-83dc-745db3b7855f.png)
and if i unroll plugin analyse it crash ardour4...

**Comment by ssj71** [comment] 2015-08-03 16:59
I'll look into this. There is no custom GUI, only the host-generated one. So the screenshot looks exactly how I would expect it. The crash shouldn't happen though. I'll check it out.

**Comment by rcspam** [comment] 2015-08-03 17:01
Must use right or left button mouse to increase/decrease ?

**Comment by ssj71** [comment] 2015-08-03 17:12
you'll have to take that up with ardour. Thats how they handle integers. I think if you hold shift and click it jumps 5 or 10 at a time.

**Comment by rcspam** [comment] 2015-08-03 17:16
Ok,  I have just download ardour4 to test it ... I thought there was sliders.
Thanks

**Comment by ssj71** [comment] 2015-08-03 17:26
I understand. I don't love that design decision ardour made myself. Thanks for testing it with other hosts!

**Comment by rcspam** [comment] 2015-08-03 17:45
It's really not usefull ! Perhaps a temporary desingn, i hope !
But is   Rakarrak developpment down ? The effects are really cool, if it is the case i hope someone(s) take up it with a better Gui...

**Comment by ssj71** [comment] 2015-08-03 17:50
No, but I just talked to the ardour developers, next ardour release will at least allow you to use scrollwheel to change the values.
Rakarrack hasn't had much development for a few years. The original devs are too busy now. I'm confident nobody's working on a new GUI for it. Feel free to contribute one though :)

**Comment by rcspam** [comment] 2015-08-03 17:58
I just write some bash scripts for my own usage, i don't know real devel language and i have no time to learn and to do that... But i think to something... why not integrate your rkr plugins to guitarix, i want to say without lv2 but native guitarix...

**Comment by rcspam** [comment] 2015-08-03 18:05
I want to say you.. not me !! ;)

**Comment by ssj71** [comment] 2015-08-03 18:19
Guitarix loads lv2 plugins. Thats the beauty of plugins (and the whole point of my effort): you can now use rakarrack effects almost anywhere. There's little point to porting them to some format that only works with 1 application.

**Comment by rcspam** [comment] 2015-08-03 18:36
I discover many things today... guitarix lv2 are native gui.... I m happy to be on vacation ;)

**Comment by rcspam** [comment] 2015-08-03 18:59
Some doen't works, i'll test them and will come back later in the week.
cu

**Comment by rcspam** [comment] 2015-08-04 16:46
Have test some rkr on guitarix and ardour4

Little enhancements if possible:
   Same setup as rakarrak by default
   Wet/Dry with -/+ button
   L/R Cross +/- with -/+ button

[1] = tested ok  [0]=doesn't work  []= no tested

[1] Lineal EQ
[1] Compressor
[1] Distortion 
[1] Echo 
[1] Chorus / Flanger
[1] Analog Phaser 
[1] Reverb 
[1] Parametric EQ 
[1] Cabinet Emulation
[1] AutoPan/Stereo Expander 
[1] Harmonizer - **Interval must be -12 to 12**
[1] Musical Delay - **Delays beside each other**
[1] WahWah 
[1] AlienWah 
[0] Derelict - **high cpu (100% 1 core ), output 'blinking'- Analisis crash Ardour 4.1**
[1] Valve  - **Stereo Negate Prefilter beside each other**
[1] Dual Flange 
[1] Ring 
[1] Exciter 
[0] DistBand  - **high cpu (100% 1 core ), output 'blinking'- Analisis crash Ardour 4.1**
[1] Arpie 
[1] Expander 
[1] Shuffle 
[0] Synthfilter - **No Sound out**
[1] VaryBand 
[1] MuTroMojo 
[1] Echoverse 
[1] CoilCrafter 
[1] ShelfBoost 
[] Vocoder 
[1] Sustainer 
[1] Sequence 
[1] Shifter 
[0] StompBox  - **high cpu (100% 1 core ), output 'blinking'- Analisis crash Ardour 4.1**
[] Reverbtron 
[] Echotron 
[] StereoHarm - no midi
[] CompBand 
[] Opticaltrem 
[] Vibe 
[] Infinity

**Comment by brummer10** [comment] 2015-08-04 17:54
To Analysis crash Ardour 4.1

This happen because the analyse tool in ardour use a fixed buffer size of 2048 samples ( if I remember right, could be 1024) 
However, this crashed all plugs which relay on fixed buffer sizes. Ardour does that even when a plug request fixed buffer sizes, so your only chance is, to check the buffersize in each run cycle and react on changes. I do that in my plugs which use oversampling and use there dynamic buffersizes for the resampler(see GxFuzz for example) and do it in my convolver wrapper, where I stream the data as long as the buffer is empty, when the given buffersize isn't equal to the one I've setup.  

regards
hermann

**Comment by ssj71** [comment] 2015-08-04 18:10
@brummer10
Thanks, that helps a lot!

@rcspam 
awesome report! Thank you!

Your request for +/- do you mean like a polarity switch (so that 127 is all wet, 0 is all dry?) I'll have to think about that because it would break backward compatibility, making the merge to rakarrack harder.

**Comment by rcspam** [comment] 2015-08-04 19:19
yes, but i think wet/dry are polarity switches in rakarrak (-64/+63)

**Comment by rcspam** [comment] 2015-08-04 19:42
@brummer10 
I don't know if it's a guitarix enhancement to do in the lv2 gui stack, but when i have tested some rkrlv2 plugins, simple switch (false/true) (e.g: Bypass) are knob 0.00 to 1.00. Am i right ?

**Comment by ssj71** [comment] 2015-08-04 19:57
@rcspam,
No, It may appear that way, but it actually just is that -64 is 100% wet, 63 is 100% dry. I just changed the range to try to make it more intuitive. Same with L/R cross. The behavior is exactly the same as the original rakarrack. I would prefer it to be 0 is all dry 127 is all wet myself.

I submitted a bug report to ardour about this issue. For now, either don't open the analysis window, or use carla as a plugin in ardour to open the ones that crash. Hopefully we can get a fix soon.

**Comment by ssj71** [comment] 2015-08-04 20:00
@rcspam 
When you report on harmonizer that the interval must be -12 to 12 what do you mean? That is already the range.

**Comment by rcspam** [comment] 2015-08-04 21:09
It works only with interval set btw -0.9 and +0.9 in guitarix and same  with ardour but impossible to see the setting... Should it be an integer like in rakarrack ?
![screenshot3](https://cloud.githubusercontent.com/assets/10021906/9072837/d39fee60-3afd-11e5-87fc-12e66f13f053.png)
![screenshot2](https://cloud.githubusercontent.com/assets/10021906/9072838/d3a34060-3afd-11e5-8bb6-794e076a7ef0.png)
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/9072839/d3a5213c-3afd-11e5-80c0-912b3de3c2ad.png)

**Comment by ssj71** [comment] 2015-08-04 22:22
@rcspam 
I've submitted another bug to ardour. The first one (crashing on plugin analysis) is already fixed in the latest ardour git. You're helping several projects today. :)

the guitarix thing seems like a bug as well. But I can't reproduce it using guitarix 0.32.3. What version are you using? Actually I think I misunderstood what you meant. Let me test it some more.

**Comment by brummer10** [comment] 2015-08-05 04:09
Well, in guitarix we haven't take care for port hints other then enumerations. 
I've fixed that now in git. We take care now for integer and toggle hints as well. So the default view will be more suitable.
However, in guitarix you could change the kind of port to use, the range to use, the step size, the order, enumeration entry's, or what ever you wont, in the detailed view. Any entry there is editable. 

By the way, great work on this port to LV2. Nice to have the (most) rakarrack plugs available in guitarix now. Only drawback here is that they are all stereo versions, are there any plans to do mono versions as well?

**Comment by rcspam** [comment] 2015-08-05 06:29
Guitarix version 0.33.0

**Comment by rcspam** [comment] 2015-08-05 07:16
@brummer10 
Thanks for , i just understood that we can change some gui thing in lv2 guitarix from 'show details'.
Really cool, is it possible to had choice btw switches, knobs, integer... in it ? Or perhaps is it too code dependent to have this kind of enhancement ?
@ssj71 
precision: guitarix 0.33 git from falktx repo

**Comment by rcspam** [comment] 2015-08-05 14:43
Tested missing above:

[i don't no] Vocoder
[0] Reverbtron 
[0] Echotron
[0] StereoHarm - no midi - like 'harmonizer' doesn't work, but a little btw interval r/l -0.9 and 0.9
[1] CompBand 
[1] Opticaltrem 
[1] Vibe 
[1] Infinity
[0] StompBox-fuzz - high cpu (100% 1 core ), output 'blinking'- Analisis crash Ardour 4.1

Regards

**Comment by ssj71** [comment] 2015-08-05 22:00
@brummer10 
Thats great news. Thanks for adding that support!
I haven't really thought about mono versions. They could be made somewhat easily, but then its 2x the code maintenance. So I don't have plans but I'd like to hear how many people are interested. 
Could guitarix just place duplicate, chained mono plugins on L and R channels if someone puts a mono after a stereo?

@rcspam sounds like the parameter not fitting in the box is also resolved in the latest ardour. So 4.2 should have both problems resolved! I still haven't had a chance to look into why these others aren't working. Hopefully I'll have some time tonight.

**Comment by trebmuh** [comment] 2015-08-05 22:31
@ssj71 : could it be a place where the Calf mono-input plugin would help ?
http://calf-studio-gear.org/
Cheers BTW for this work, that's great to see.

**Comment by ssj71** [comment] 2015-08-05 22:47
@trebmuh possibly, but I think this case is more a limitation of guitarix as an lv2 host. They currently only support stereo plugins at the end of the chain IIRC. There are several ways it could be changed to handle arbitrary ordering of mono and stereo plugins (i.e. ardour does this automatically) but it requires somebody writing the code for guitarix.

**Comment by brummer10** [comment] 2015-08-06 01:27
For us, it isn't a limitation, it's a design decision. For production one can use our LV2 plugs in the host of choice, but guitarix is focused on live usage. We give the CPU usage a high priory in our work. That allow us to go with real low latency. Doubling channels in the host, would negate that. Often enough, you didn't need stereo FX at all for your guitar. 
Mono versions would be welcome here for all plugs, but special for the:
[1] Linear EQ
[1] Compressor
[1] Distortion
[1] Parametric EQ
[1] WahWah
[1] AlienWah
[1] Exciter
[1] Expander
[1] Shuffle
[1] Sustainer

@rcspam 
Currently the kind of controller  is bounded to the kind of parameter to control. So change the kind of parameter will change the controller in the interface. 
we do also support interfaces for LV2 plugs build with glade, this way one could indeed select any aspect of the native UI representation in the guitarix rack. 
But it require a bit more inside knowledge.

**Comment by rcspam** [comment] 2015-08-06 05:33
Btw, Echotron & Reverbtron  don't appear in guitarix list...

**Comment by ssj71** [comment] 2015-08-06 15:51
@brummer10 thanks for the clarification. It makes sense why then you'd want mono versions. With the short list I'll consider it. I didn't really want to go refactor 40 effects.

@rcspam those two effects have more feature requirements of the host, which I don't think guitarix supports.

**Comment by ssj71** [comment] 2015-08-07 15:19
@rcspam ok, I just pushed a change that adds optimizations and uses a faster algorithm for the waveshaping effects (stompbox, distband, derelict). If you can, please test and verify that it works on your system too.

**Comment by rcspam** [comment] 2015-08-07 15:40
Ok they work well now...
I wait for Synthfilter and [Stereo]Harmonizer and then...  wake up in the morning with a zomby woof behind my eyes  ;)

**Comment by ssj71** [comment] 2015-08-08 06:27
well i figured out harmonizer. synth and stereoharm will have to wait until tomorrow (or next week maybe).

**Comment by ssj71** [comment] 2015-08-10 17:33
synth and stereo harm were fixed Saturday morning. I'm going to close this issue and make a few new ones for what issues remain. Thanks to all who participated.

**Closed as completed by ssj71** 2015-08-10 17:33 UTC

**Comment by rcspam** [comment] 2015-08-10 17:56
harmonizer works but not stereoharm ...

**Comment by ssj71** [comment] 2015-08-10 18:01
hmm. It was working for me. :( Do you get any sound out? What settings?

**Comment by rcspam** [comment] 2015-08-10 18:50
[Here](https://dl.dropboxusercontent.com/u/2677320/essai.mp3) a audio file:
First rec: normal sound
Second rec: Rackarrack SereoHarmo with this setting
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/9180081/cc34538a-3fa0-11e5-85f7-e1144dd02186.png)
Third rec: Guitarix rkrlv2 with same setting:
![screenshot3](https://cloud.githubusercontent.com/assets/10021906/9180086/cdb7158a-3fa0-11e5-8fbd-531e713d7100.png)

**Comment by brummer10** [comment] 2015-08-12 02:15
to fix this, add in rkrlv2.c, after RKRLV2\* plug = (RKRLV2*)handle; in line 3402 

plug->sharm->adjust(5,nframes);

**Comment by brummer10** [comment] 2015-08-12 04:29
@ssj71 
Also, you may wont to fix the wetdry_mix 
line 190 
`-   plug->output_l_p[i] = plug->input_r_p[i] * v2 + plug->output_l_p[i] * v1;` 
`+ plug->output_l_p[i] = plug->input_l_p[i] * v2 + plug->output_l_p[i] * v1;`

**Comment by ssj71** [comment] 2015-08-12 05:10
@brummer10 thank you very much! You make it a pleasure to write open source software.

@rcspam I've made the change in master, please test and let me know if it still has any problems. Right now the "select chord" mode still isn't working right, but at least the basic shifting should.

**Comment by rcspam** [comment] 2015-08-12 06:39
Ok it works !   Does L/R Crossover work ?! My feeling is  it doesn't work in rakarrack neither in rkrlv2 , but i'm perhaps wrong !
Thank you both @brummer10 @ssj71 (and other "libre software" devel) to ensure that playing music is so cool on Linux !!!

**Comment by brummer10** [comment] 2015-08-12 07:15
No, it doesn't. 
It could be fixed by move the crossover logic behind the upsampling in the output.  
from
`for (i = 0; i < nPERIOD; i++) {`
`outil[i] = templ[i];`
`outir[i] = tempr[i];`
`}`
to
`for (i = 0; i < period; i++) {`
`efxoutl[i] = templ[i] * gainl * (1.0f - lrcross) + tempr[i] * gainr * lrcross;`
`efxoutr[i] = tempr[i] * gainr * (1.0f - lrcross) + templ[i] * gainl * lrcross;`
`}`

**Comment by rcspam** [comment] 2015-08-12 07:50
I want to test your fix but where is: 

```
for (i = 0; i < nPERIOD; i++) {
outil[i] = templ[i];
outir[i] = tempr[i];
}
```

if i search in StereoHarm.C just find line 125:

```
    for (i = 0; i < nPERIOD; i++) {


        outil[i] = templ[i] * (1.0f - lrcross) + tempr[i] * lrcross;
        if (outil[i] > 1.0)
            outil[i] = 1.0f;
        if (outil[i] < -1.0)
            outil[i] = -1.0f;

        outir[i] = tempr[i] * (1.0f - lrcross) + templ[i] * lrcross;
        if (outir[i] > 1.0)
            outir[i] = 1.0f;
        if (outir[i] < -1.0)
            outir[i] = -1.0f;

    }
```

**Comment by brummer10** [comment] 2015-08-12 07:57
I guess it's better to let @ssj71 have a look at it, and test it if he checked it in the right way. 
My fix works, but could properly be better implemented.

**Comment by rcspam** [comment] 2015-08-12 08:14
I have replace line 168 

```
 for (i = 0; i < period; i++) {
        efxoutl[i] = templ[i] * gainl;
        efxoutr[i] = tempr[i] * gainr; 
    }
```

by your code

```
for (i = 0; i < period; i++) {
       efxoutl[i] = templ[i] * gainl * (1.0f - lrcross) + tempr[i] * gainr * lrcross;
       efxoutr[i] = tempr[i] * gainr * (1.0f - lrcross) + templ[i] * gainl * lrcross;
}
```

... and it works ;)

**Comment by brummer10** [comment] 2015-08-12 09:05
That's it, yea. 
I guess you know, when @ssj71 fixed it in the repository, you need to do a 
`git checkout master`
or a 
`git stash`
to switch back to the master source, before you are able to checkout the repository again.

**Comment by rcspam** [comment] 2015-08-12 09:08
Some rkrlv2 are an invert panning.
efxoutl[i] and efxoutr[i] are inverted in this files:

```
[rkrlv2/src] $ grep -e  "efxoutl\[i\].*panning;" *.C
Chorus.C:            efxoutl[i] *= panning;
Distorsion.C:        efxoutl[i] = lout * 2.0f * level * panning;
DynamicFilter.C:        efxoutl[i] *= panning;
Harmonizer.C:        efxoutl[i] = templ[i] * gain * panning;
MBDist.C:        efxoutl[i] = l * 2.0f * level * panning;
NewDist.C:        efxoutl[i] = lout * level * panning;
RBEcho.C:        efxoutl[i] = (ipingpong*ldl + pingpong *ldelay->delay_simple(0.0f, ltime, 2, 0, 0)) * lpanning;
Ring.C:        efxoutl[i] = lout * level * panning;
Valve.C:        efxoutl[i] = lout * 2.0f * level * panning;

```

**Comment by rcspam** [comment] 2015-08-12 09:23
@brummer10 
yes, thanks

**Comment by rcspam** [comment] 2015-08-12 10:15
I have propose a pull request https://github.com/ssj71/rkrlv2/pull/6 ...

**Comment by ssj71** [comment] 2015-08-12 15:48
The LRCross is supposed to be handled before the pitch shifting (StereoHarmonizer.C:128 and ln 134). The code is there. I'll have to look into why its not working.

**Comment by brummer10** [comment] 2015-08-12 16:03
But, that makes no sense, there is nothing to LRCross before the shift, as, only the applied effect is to Cross here, not the original (input) signal. 
The effect get applied to a dry input signal and mixed in then by the wet/dry controller. 
By the way, nearly all of the effects suffer from this logic error.

**Comment by ssj71** [comment] 2015-08-12 16:40
@brummer10 
its a design decision made by the original developers. LR cross is just mixing the left and right channels. With a stereo in and stereo out you could mix it in either place (pre or post effect). This happened because it is a guitar effects program which really should be mono in (you got this right in guitarix). So if you only have audio on 1 of the stereo in channels, you use pre-effect LR cross to get a strong stereo image in the effect out. In a linear operation it makes absolutely no difference if pre or post. 

In this case, its a question of whether you want the L and R detuning to stay hard L&R or mix together. I agree that its probably more useful to mix the post-processed channels. There are cases for both methods. I'll talk to the original devs about it.

**Comment by brummer10** [comment] 2015-08-12 17:05
> its a design decision made by the original developers. LR cross is just mixing the left and right channels.  
> So if you only have audio on 1 of the stereo in channels, you use pre-effect LR cross to get a strong stereo image in the effect out.

If so, then it is bad by design. Why the hell you would implement such a algorithm in any effect,  instead write a single plug to do this once for all?
I know crossover as a pan to move the applied effect over the channels, and, in the LV2 plugs, that is the only expected behave for it. Special in respect to the wet/dry control. 

Especial in the stereo-harmoniser it's nice to mix (LRCross) both sides with different intervals.

**Comment by ssj71** [comment] 2015-08-12 17:28
not a bad design. Just different. With the traditional implementation you could just connect a guitar input to one channel, turn up LR cross, and you'd hear both the L&R intervals. With the new implementation, you would have sound in both channels, but it would only be the L interval. 

> Why would you implement such a algorithm in any effect, instead write a single plug to do this once for all?

I agree. The whole project just grew organically from the zynaddsubfx code. Everything else was copy/pasted and changed. Its got a lot of issues, but I'm trying to get everything functioning then merge back to the original codebase, then refactor.

I think you are right though, that it makes most sense to do post effect mixing. I am waiting to hear back from the original authors before changing everything though.

**Comment by brummer10** [comment] 2015-08-12 17:54
> With the new implementation, you would have sound in both channels, but it would only be the L interval. 

When you feed a mono signal in a stereo effect, in just one channel. ? 
I'm not aware of any host which will do that. And even Rakarrack users are used to connect there Guitar's to both input channels.
The question is, is it supposed to mix the dry signal (bad, because you lose volume by mixing it this way, therefore you need a other algorithm to do it right), or the wet signal (expected), or both (questionable). 
I would go for only the wet.

**Comment by ssj71** [comment] 2015-08-12 19:43
I think you are right. I will make this change.

I'd like to close this issue (since the 1st reported issue is now resolved) and continue discussion in the other issues I've opened.

Thanks guys.
